
- gz_topic_name: "/model/Nao/joint/HeadPitch/0/cmd_pos" 
  ros_topic_name: "/HeadPitch/cmd_pos" 
  ros_type_name: "std_msgs/msg/Float64" 
  gz_type_name: " gz.msgs.Double" 
  direction: ROS_TO_GZ


- gz_topic_name: "/model/Nao/joint/HeadYaw/0/cmd_pos"
  ros_topic_name: "/HeadYaw/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LAnklePitch/0/cmd_pos"
  ros_topic_name: "/LAnklePitch/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LAnkleRoll/0/cmd_pos"
  ros_topic_name: "/LAnkleRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LElbowRoll/0/cmd_pos"
  ros_topic_name: "/LElbowRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LElbowYaw/0/cmd_pos"
  ros_topic_name: "/LElbowYaw/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LHipPitch/0/cmd_pos"
  ros_topic_name: "/LHipPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LHipRoll/0/cmd_pos"
  ros_topic_name: "/LHipRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LHipYawPitch/0/cmd_pos"
  ros_topic_name: "/LHipYawPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LKneePitch/0/cmd_pos"
  ros_topic_name: "/LKneePitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LShoulderPitch/0/cmd_pos"
  ros_topic_name: "/LShoulderPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LShoulderRoll/0/cmd_pos"
  ros_topic_name: "/LShoulderRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/LWristYaw/0/cmd_pos"
  ros_topic_name: "/LWristYaw/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RAnklePitch/0/cmd_pos"
  ros_topic_name: "/RAnklePitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RAnkleRoll/0/cmd_pos"
  ros_topic_name: "/RAnkleRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RElbowRoll/0/cmd_pos"
  ros_topic_name: "/RElbowRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RElbowYaw/0/cmd_pos"
  ros_topic_name: "/RElbowYaw/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RHipPitch/0/cmd_pos"
  ros_topic_name: "/RHipPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RHipRoll/0/cmd_pos"
  ros_topic_name: "/RHipRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RHipYawPitch/0/cmd_pos"
  ros_topic_name: "/RHipYawPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RKneePitch/0/cmd_pos"
  ros_topic_name: "/RKneePitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RShoulderPitch/0/cmd_pos"
  ros_topic_name: "/RShoulderPitch/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RShoulderRoll/0/cmd_pos"
  ros_topic_name: "/RShoulderRoll/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "/model/Nao/joint/RWristYaw/0/cmd_pos"
  ros_topic_name: "/RWristYaw/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  
- gz_topic_name: "/clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS